train:
  seed: 1999
  epochs: 50
  interval: 1
  pretrain: backbone/sp_unet_backbone.pth
  save_epoch: 505
  grad_clip: 0.0

test:
  seed: 1999
  test_topk_per_scene: 100
  test_score_thresh: 0.0
  test_npoint_thresh: 100

dataloader:
  train:
    batch_size: 2
    num_workers: 8 
    persistent_workers: True
  val:
    batch_size: 1
    num_workers: 4
    persistent_workers: True
  test:
    batch_size: 1
    num_workers: 2
    persistent_workers: True

data:
  train:
    type: scannetv2_sample_graph_edge
    data_root: data/
    prefix: train
    suffix: .pth
    training: True
    mode: 4
    aug: True
    with_elastic: True
    use_xyz: True
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 2500000
    max_des_len: 330
    lang_num_max: 8
  val:
    type: scannetv2_sample_graph_edge
    data_root: data/
    prefix: val
    suffix: .pth
    training: False
    mode: 4
    aug: False
    with_elastic: False
    use_xyz: True
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 2500000
    max_des_len: 330
    lang_num_max: 32
  test:
    type: scannetv2_sample_graph_edge
    data_root: data/
    prefix: test
    suffix: .pth
    training: False
    mode: 4
    aug: False
    with_elastic: False
    use_xyz: True
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 2500000
    max_des_len: 330
    lang_num_max: 32

model:
  input_channel: 6
  blocks: 5
  block_reps: 2
  media: 32
  normalize_before: True
  return_blocks: True
  pool: mean
  decoder: 
    num_layer: 6
    d_model: 256
    nhead: 8
    hidden_dim: 1024
    dropout: 0.0
    activation_fn: gelu
    iter_pred: True
    attn_mask: True
  criterion:
    loss_weight: [1.0, 1.0, 0.5, 0.1]
    loss_fun: focal
  test_cfg:
    topk_insts: 100
    score_thr: 0.0
    npoint_thr: 100
  norm_eval: False
  fix_module: [ 
              'text_encoder',
              ]

optimizer:
  type: AdamW
  lr: 0.0001
  weight_decay: 0.0005
  paramwise_cfg:
   text_encoder:
     lr_mult: 0.001
   input_conv:
     lr_mult: 0.01
   unet:
     lr_mult: 0.01
   output_layer:
     lr_mult: 0.01
   decoder:
     lr_mult: 1.0

lr_scheduler:
  type: MultiStepLR
  milestones: [26, 34, 42]
  gamma: 0.5
